version: '3'
services:
  usersDb:
    image: mariadb
    volumes:
      - ../db/leare_users_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_app_development
    ports:
      - "3307:3307"

#docker exec leare_users_ms-users_web-1 rails db:migrate
  users_web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - usersDb
    environment:
      DATABASE_URL: mysql2://root:password@usersDb/my_app_development